server:
  port: 8888

spring:
   application:
     name: config-service
   cloud:
     config:
       server:
         git:
           uri: file://C:\Users\jaedeok\study\spring-boot\spring-msa\configuration-service\local-git-repo