spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}328b524892f2890d0c1075a9aeeab28c98503f8f62d6514bb63e863ac1a3b4f2'

token:
  expiration_time: 864000000 # 60 * 60 * 24 * 1000
  secret: user_token_native_user_service_default

gateway:
  ip: 192.168.0.2
